[package]
name = "comparison"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
teloxide = { workspace = true }
serde = { workspace = true }
rkyv = { workspace = true }
wincode = { workspace = true, features = ["derive"] }
bitcode = { workspace = true, features = ["derive"] }
easy_callback = { path = "../../", features = [
    "rkyv",
    "wincode",
    "postcard",
    "bitcode",
    "rmp",
    "ciborium",
] }
